version: '2'

services:
  app:
    build: .
    image: ludovic-bouguerra/travis-example
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
